[package]
name = "random-pick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "randompicklib"
path = "src/lib.rs"

[[bin]]
name = "random-pick"
path = "src/main.rs"

[dependencies]
