[package]
name = "randompick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "randompicklib"
path = "src/lib.rs"

[[bin]]
name = "randompick"
path = "src/main.rs"

[dependencies]
rand = "0.8.0"
